### ISSUE TITLE
webcomponents.dev example broken

### ISSUE THREAD

**Issue by ontoneio** [lume/element#20]
https://studio.webcomponents.dev/edit/y2DKkUqt7I1tc3L6CCWR/src/index.jsx?p=stories

Throws an error and doesn't start up.

![image](https://github.com/lume/element/assets/24515434/b3fdc1cf-344a-4ff9-b945-a5ba7c4f699e)

**Comment by trusktr** [comment]
Ah, that's unfortunate that it broke. Thanks for reporting this!

When I first made that demo, webcomponents.dev didn't support versioning libraries, so if a library has a breaking change a deck could simply break. 

Here's a fork of that example with updated import statements so that

- it uses `signalify` (it was previously named `reactify`, and lume element used to re-export it from classy-solid)
- imports `html` from solid-js which lume element used to also re-export 

https://studio.webcomponents.dev/edit/B9KHyaJjJVj1YrTPPtKn/src/index.jsx

I see that webcomponents.dev allows modifying package.json now. Maybe I can update examples so that lib versions are locked and demos won't break.
