### ISSUE TITLE
Live Demo "Using JSX and decorator syntax" throw error.

### ISSUE THREAD

**Issue by kouhei** [lume/element#8]
When I open the demo page(https://webcomponents.dev/edit/EJ5VTuaaO0Iwq3APUFMe), the code throws error below.

> _$currentContext is not a function
[src/index.stories.jsx (12:22)]()
>> TypeError: _$currentContext is not a function
    at https://webcomponents.dev/42890220-93bd-11ec-b7a1-81c82af0ebbf/web_modules/EJ5VTuaaO0Iwq3APUFMe/dist/index.stories.js:17:19
    at story1 (https://webcomponents.dev/42890220-93bd-11ec-b7a1-81c82af0ebbf/web_modules/EJ5VTuaaO0Iwq3APUFMe/dist/index.stories.js:19:3)
    at n.parameters.__isArgsStory (https://webcomponents.dev/assets/__virtual_entry_render_addon.hash.js:42:3037)
    at https://webcomponents.dev/assets/__virtual_entry_render_addon.hash.js:42:5354
    at vo (https://webcomponents.dev/assets/__virtual_entry_render_addon.hash.js:43:1125)

BROWSER: Google Chrome: 98.0.4758.102

**Comment by trusktr** [comment]
Hey, thanks for reporting. This is because webcomponents.dev does not yet support versioned Babel compiler and plugins, so after a while it broke once the dependencies received updates with breaking changes.

cc @georges-gomes @webcomponents-dev

Let's remove these links, then we can add demos on the main site.

**Comment by trusktr** [comment]
Links have since been removed and the README links to working demos. @georges-gomes if you can get us back and running I would love to include links!
